[error] akka.stream.impl.io.ConnectionSourceStage$$anon$2$$anon$1: Bind failed because of Address already in use: bind
[error] Caused by: java.net.BindException: Address already in use: bind
[error] 	at sun.nio.ch.Net.bind0(Native Method)
[error] 	at sun.nio.ch.Net.bind(Net.java:433)
[error] 	at sun.nio.ch.Net.bind(Net.java:425)
[error] 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
[error] 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
[error] 	at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:56)
[error] 	at akka.io.TcpListener.<init>(TcpListener.scala:53)
[error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error] 	at akka.util.Reflect$.instantiate(Reflect.scala:65)
[error] 	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)
[error] 	at akka.actor.Props.newActor(Props.scala:213)
[error] 	at akka.actor.ActorCell.newActor(ActorCell.scala:626)
[error] 	at akka.actor.ActorCell.create(ActorCell.scala:652)
[error] 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:525)
[error] 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:547)
[error] 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
[error] 	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
[error] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[error] 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[error] 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[error] 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error] 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] (Compile / run) java.lang.reflect.InvocationTargetException
